name: Build and deploy to github pages
on:
  push:
    branches:
      - dev

jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      GHC_VERSION: '8.8.2'
    steps:
      - name: Checkout dev
        uses: actions/checkout@master

      - name: Build with 11ty
        uses: TartanLlama/actions-eleventy@master
        with:
          args: --input=src

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          cname: willwolf.me
          publish_dir: _site